### PR TITLE
xcode 10 and Swift 4.2 support

### PR DESCRIPTION
**Pull request by ergunkocak**
I guess title is self explanatory :)

### CODE REVIEW

**Comment by snowtema** [comment]
What about this PR? When it could be approved?

**Comment by nicolelehrer** [comment]
Thanks for your contribution @ergunkocak! I noticed some more changes would be necessary for the example project to run. Would you be able to 
- cd into `PlayerKit/Example ` and run `pod install`
- Update the project settings to be compatible with Swift 4.2 and do the remaining migration (I think the files still needing some Swift API changes include `AppDelegate.swift` and `RegularPlayer.swift`)
- double check the example builds and runs

Then I'll give it another test and we'll get this merged! Thank you!

**Comment by SalehAlDhobaie** [comment]
is this project deprecated ?

**Comment by jasonhawkins** [comment]
Hey @SalehAlDhobaie, no this project is still under active development. We're working on upgrading several projects to support Xcode 10.2 and Swift 4.2 at the moment, and are hoping to complete that work this month.

**Comment by rpassis** [comment]
Closing this in favor of #61

**Pull request closed without merging**
