### PR TITLE
Merging Release/1.0.0 branch

### PR DESCRIPTION
**Pull request by mikew-personal**
- Merging in the release 1.0.0 branch

### CODE REVIEW

**Comment by ghking** [comment]
@mikew-personal Lookin good

**Comment by mikew-personal** [comment]
build this please

**Comment by wilrnh** [comment]
build this please

**Comment by cameo-github** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Message">
          1 Message
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:book:</td>
      <td data-sticky="false">Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.002) seconds</td>
    </tr>
  </tbody>
</table>

See build details on [CircleCI](https://circleci.com/gh/vimeo/PlayerKit/5)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Pull request merged**
